khang

diff --git a/.github/workflows/test-java.yml b/.github/workflows/test-java.yml
--- a/.github/workflows/test-java.yml
+++ b/.github/workflows/test-java.yml
@@ -8,15 +8,18 @@ on:
 
 jobs:
   build:
+    name: Run Tests on Windows
     runs-on: windows-latest
 
     steps:
-      - uses: actions/checkout@v3
+      - name: Checkout source code
+        uses: actions/checkout@v3
 
-      - uses: actions/setup-java@v3
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
         with:
           java-version: '17'
           distribution: 'temurin'
 
-      - name: Run tests
-        run: mvn clean test 
+      - name: Build and run tests
+        run: mvn clean install || (echo "Build or tests failed!" && exit 1) 
